### ISSUE TITLE
건의사항: 핸즈온 은 동영상으로 내용을 찍어서 과제 형식으로 실습하면 어떨지 건의합니다.

### ISSUE THREAD

**Issue by ghojeong** [cb-contributhon/cb-coffeehouse#10]
두번의 온라인 회의에서 핸즈온 활동을 했는데, 
중간에 놓치기도 하고,  회의가 끝나고 다시 복습하기가 쉽지 않았습니다.

어차피 회의 영상을 보면서 따라 실습을 하는건데,
라이브 영상이 아니라, 스크린 녹화 + 마이크 녹음으로 미리 영상을 만들어서,
온라인 미팅 전까지 실습을 해오도록 하고,
미팅 시간에는 녹화된 영상을 따라했을때, 잘 안되던 내용들을 도와주는 시간을 가지면 어떨까 건의해 봅니다.

**Comment by hermitkim1** [comment]
녹화 영상을 공유하는 의견 좋다고 생각합니다.
한편, 영상을 미리 만들어 공유하는 것에 대해서는 생각해볼 부분이 많은 것도 사실 입니다.

- 준비된(예, 필수 패키지가 이미설치 됨 등) 환경에서 영상을 제작할 시 놓치는 부분 존재
- 미션 및 가이드 문서 구상, 테스트, 공유에 더하여 별도 영상을 준비하시는 노고
- 멘티님들

**Comment by yunkon-kim** [comment]
클릭 실수로 미션을 닫았다 오픈했네요ㅎㅎ

영상을 공유하면 분명 장점이 있을 것 같습니다.

멘토와 멘티 한명한명은 다양한 상황에서 컨트리뷰톤에 참여하고 계시기 때문에 "멘토님들께서 미리 영상을 만들어 배포하는것", "멘티님들께서 미팅 시간전까지 실습 진행", "미팅시간에는 잘되는 부분에 집중"에 대해서는 호불호가 있을 것 같습니다.

그리고 현재도 멘토님께서 미션과 가이드를 구상, 테스트, 내용정리 후 미리 배포하시고 있고, 미션을 수행후 핸즈온을 들으며 보완하는 분도 있으시며, 시간상의 제약으로 핸즈온을 들은 후 미션을 수행하시는 분도 있습니다.

또한, 실시간 핸즈온에서 소통하며 문제를 해결하는 긍정적인 부분도 있고요.

우선 제 개인적인 의견은 Cloud-Barista 컨트리뷰톤이 중반부에 접어든 만큼 현재 프로세스 변경보다는 1. 미션 공지, 2 미션 수행, 3 핸즈온 프로세스는 유지하고, 온라인 회의 미팅영상을 녹화하여 공유하는게 좋을 것 같습니다.

정확한 사항은 논의가 필요하고요. 논의 후에 공유 드리겠습니다.

Cloud-Barista's Coffeehouse를 이용해 주셔서 감사드리고요

이곳은 개념, 용어, 명령어, 방법, 사용법 등을 질의 또는 알기쉽게 설명하는 공간이기에 컨트리뷰톤 운영과 관련한 건의 또는 질의사항은 Slack Q&A 남겨주시기 바랍니다 😄

**Comment by ghojeong** [comment]
넵. 좋은 답변 감사합니다. 질의사항 관련 내용은 Close 하도록 하겠습니다.
