### ISSUE TITLE
Terraform 을 클라우드 바리스타 프로젝트에 도입할 계획이 있나요?

### ISSUE THREAD

**Issue by ghojeong** [cb-contributhon/cb-coffeehouse#9]
# [Terraform](https://www.terraform.io/)

클라우드 관련해서 이것저것 찾아보다가, Terraform 이라는 Go 언어로 된 오픈소스 프로젝트가 있다는 것을 알게 되었습니다.

"Infrastructure as Code" 라는 용어로, Terraform 이 스스로를 표현하고 있는데,
CB-Tumblebug 을 구현할 때, Terraform 을 활용하면 텀블벅에서 구현하고자 하는 기능들을 더 쉽게 구현할 수 있지 않을까 라는 생각이 들었습니다.

전문가분들이 이미 많이 계신지라, 이미 Terraform 잘 알고 계실 것 같아서,
정보 공유 보다는 궁금해서 여쭈어봅니다.

**Comment by yunkon-kim** [comment]
저희도 Terraform을 몇 차례 리뷰 및 분석 하였는데요.

결론부터 말씀 드리면 도입계획은 아직 없는 것으로 알고 있으나, Terraform이 시장에서 긍정적인 반응을 보이는 만큼 앞으로도 관심을 가지고 지켜볼 것입니다.

도입 계획이 없었던 이유는 "구체화"와 "일반화"의 차이가 존재하지 때문이라고 생각합니다.

Terraform에서 내세우는 "Infrastructure as Code"는 각 클라우드 사업자가 Console에서 제공하는 각기 다른 많은 기능/서비스를 대부분 유지하되 코드로 관리하는 장점을 갖습니다. 구체적으로 기능/서비스 하나하나를 사용할 수 있겠지만, 한편으로는 하나하나를 모두 알아야 사용할 수 있어 전문성이 요구됩니다.

Cloud-Barista는 각 클라우드 사업자가 제공하는 기능/서비스를 분석하여 각기 다른 기능/서비스를 제외하고 공통 기능/서비스를 도출하여 일반화 하였습니다. 일반화로 사용자가 각 클라우드의 상세한 기능을 신경쓰지 않고 각 클라우드의 자원을 이용할 수 있기 때문에 손쉬운 사용이 가능합니다.

**Comment by ghojeong** [comment]
질문 관련된 내용인지라, Close 하도록 하겠습니다.

**Comment by yunkon-kim** [comment]
고정완(@ghojeong ) 멘티님께,

안녕하세요. 아침에 생각을 조금 해보았는데요.

고정환 멘티님의 시각에서 Terraform을 "간략히" 정리하여 소개해 주신다면 멘티님들께 트렌드를 소개하는데 도움 될 것 같습니다.

강조 드리고 싶은 부분은 **이런 Product이 있어요 정도의 "아주 간략한 설명"** 입니다.

혹시 가능하실지요?

**Comment by ghojeong** [comment]
저도 Terraform 에 대해서는 지난주에 알게 된지라, 제대로 설명하기 어려울 것 같습니다.
인프라 관련해서는 개발 경험이 전혀 없는지라, (인프라 접근 권한이 없는 프론트엔드 개발자 입니다 ㅠ.ㅠ)
제가 잘못 알고 있는 부분이 많고, 잘못 설명하게 될 것 같아서요.

오히려 저도 Terrraform 이 나오기까지의 히스토리와 트렌드를 알고 싶네요.

**Comment by yunkon-kim** [comment]
내용 정리로 부담 드리려던 것은 절대로 아니고요.

저는 알아가는 과정을 정리하는데 의미가 있고, 그 결과로 멋진 설명이 완성된다고 생각해서 제안 드렸던 거에요 ㅎㅎ

클라우드 인프라, Terraform이 등장하기 까지의 트렌드 등을 조금씩 정리하다 보면 멋진 한판이 나올 것 같은 생각 입니다.

일단 본 Issue는 Close 하겠지만 차후 Coffeehouse에서 다른 관점으로 바라본다면 좋은 주제가 될 것 같습니다.

방향성이 잡히면 Issue 등록 하겠습니다. 그때 많은 의견 부탁드립니다 😄
